version: '3.8'

services:
  magicmatch:
    build:
      context: .
      target: runtime
    image: cgg/magicmatch
    entrypoint: ["magicmatch"]
    volumes:
      - ./data:/workspace/data
    working_dir: /workspace

  genecast:
    build:
      context: .
      target: runtime
    image: cgg/genecast
    entrypoint: ["cast"]
    volumes:
      - ./data:/workspace/data
    working_dir: /workspace

  generage:
    build:
      context: .
      target: runtime
    image: cgg/generage
    entrypoint: ["generage"]
    volumes:
      - ./data:/workspace/data
    working_dir: /workspace

  genefuse:
    build:
      context: .
      target: runtime
    image: cgg/genefuse
    entrypoint: ["genefuse"]
    volumes:
      - ./data:/workspace/data
    working_dir: /workspace

  cogent_utils:
    build:
      context: .
      target: runtime
    image: cgg/cogent_utils
    entrypoint: ["create_cogent.sh"]
    volumes:
      - ./data:/workspace/data
    working_dir: /workspace

  clustt_utils:
    build:
      context: .
      target: runtime
    image: cgg/clustt_utils
    entrypoint: ["mcl_clustering.sh"]
    volumes:
      - ./data:/workspace/data
    working_dir: /workspace
