services:
  cgg-toolkit:
    build:
      context: .
      target: runtime
    image: cgg-toolkit:latest
    volumes:
      - ./data:/workspace/data
    working_dir: /workspace
    entrypoint: ["/bin/bash", "-c"]
    command: ["echo 'Available commands: magicmatch, cast, generage, prss33, genefuse, ssearch35, create_cogent.sh, mcl_clustering.sh' && /bin/bash"]

  # Individual tool aliases (all using the same built image)
  magicmatch:
    image: cgg-toolkit:latest
    entrypoint: ["magicmatch"]
    volumes:
      - ./data:/workspace/data
    working_dir: /workspace

  genecast:
    image: cgg-toolkit:latest
    entrypoint: ["cast"]
    volumes:
      - ./data:/workspace/data
    working_dir: /workspace

  generage:
    image: cgg-toolkit:latest
    entrypoint: ["generage"]
    volumes:
      - ./data:/workspace/data
    working_dir: /workspace

  genefuse:
    image: cgg-toolkit:latest
    entrypoint: ["genefuse"]
    volumes:
      - ./data:/workspace/data
    working_dir: /workspace

  cogent:
    image: cgg-toolkit:latest
    entrypoint: ["create_cogent.sh"]
    volumes:
      - ./data:/workspace/data
    working_dir: /workspace

  clustt:
    image: cgg-toolkit:latest
    entrypoint: ["mcl_clustering.sh"]
    volumes:
      - ./data:/workspace/data
    working_dir: /workspace